import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'
import { Header } from './components/Header'
import { Nav } from './components/Nav'

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${sora.className}  leading-relaxed overflow-hidden bg-[radial-gradient(ellipse_at_top_left,_var(--tw-gradient-stops))] from-gray-900 via-purple-900 to-purple-900  text-white font-sora`}
      >
        <div className="w-full h-screen  overflow-hidden">
          <Header />
          {children}
          <Nav />
        </div>
      </body>
    </html>
  )
}
